image: php:7.2.0

pipelines:
  default:
    - step:
        name: pre build app
        caches:
          - composer
          - node
        script:
          - echo "pre build app"
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
#          - composer run lint:php
#          - composer run fix:php
          - curl -sL https://deb.nodesource.com/setup_10.x | bash -
          - apt-get install -y nodejs
          - npm install
#          - npm run fix:scripts
#          - npm run fix:styles
          - npm run encore -- production
  #  bookmarks:                      # add the 'bookmarks' section
  #    release-*:                    # specify the bookmark
  #      - step:                     # define the build pipeline for the bookmark
  #          name: Build and release
  #          script:
  #            - npm install
  #            - npm test
  #            - npm run release
  custom:
    develop:
      - step:
          deployment: dev
          name: deploy to dev
          max-time: 180
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER
                COMMAND: 'cd /var/repository/eso/ && git fetch origin && git reset --hard origin/$BITBUCKET_BRANCH && composer install && npm install && npm run encore -- production && ./vendor/bin/jedi env:init default && php migrator migrate && ./vendor/bin/jedi cache:clear'
                DEBUG: 'true'
