version: '3.6'
services:
  mariadb:
    image: mariadb:10.4
    container_name: is_maria
    ports:
      - 43501:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: is
      MYSQL_USER: is
      MYSQL_PASSWORD: is
    volumes:
      - ./docker/maria/dump.sql:/home/dump.sql
      - ./var/data/maria-db-files:/var/lib/mysql
      - ./var/log/docker/mysql:/var/log/mysql
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rost_phpmyadmin
    ports:
      - 43502:80
    environment:
      - PMA_HOST=mariadb
    links:
      - mariadb:db
    depends_on:
      - mariadb
    networks:
      - internal
  php:
    build: ./docker/php
    container_name: is_php
    ports:
      - 43503:9001
    volumes:
      - .:/var/www/html
      - ./var/log/php:/var/log/php7
      - ./docker/php/symfony.pool.conf:/etc/php7/php-fpm.d/symfony.pool.conf
      - ./docker/php/symfony.ini:/etc/php7/conf.d/symfony.ini
      - ./docker/php/symfony.ini:/etc/php7/cli/conf.d/symfony.ini
    links:
      - mariadb
    networks:
      - internal
  nginx:
    image: nginx:alpine
    container_name: is_nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache
    networks:
      - internal
  apache:
    image: httpd:2.4-alpine
    container_name: is_apache
    links:
      - php
    volumes:
      - .:/var/www/html:cached
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28
